name: Nix Flake CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  nix-flake-check:
    name: Nix Flake Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Show Nix version
        run: nix --version

      - name: Build rv
        run: nix build --quiet

      - name: Print rv help
        run: result/bin/rv --help

      - name: Install a ruby version
        run: |
          result/bin/rv ruby install ruby-3.4.5
          result/bin/rv ruby run ruby-3.4.5 -- --version
